export const envVars = {
    CCS3_DEVICE_TIMER_SERVICE_STATIC_FILES_PATH: 'CCS3_DEVICE_TIMER_SERVICE_STATIC_FILES_PATH',
    CCS3_DEVICE_TIMER_SERVICE_NO_STATIC_FILES_SERVING: 'CCS3_DEVICE_TIMER_SERVICE_NO_STATIC_FILES_SERVING',
};
